services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mapngo-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - public_network


  backend:
    build: .
    container_name: mapngo-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mapngo-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - public_network

  frontend:
    build: ../frontend
    container_name: mapngo-frontend
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"
    networks:
      - public_network
volumes:
  pgdata:

networks:
  public_network:

